import "dotenv/config";
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from "prisma/config";
const databaseUrl = process.env.DATABASE_URL || "file:./dev.db";
export default defineConfig({
    schema: "prisma/schema.prisma",
    migrations: {
        path: "prisma/migrations",
    },
    datasource: {
        // Use the environment DATABASE_URL if available, otherwise fall back to dev.db
        url: databaseUrl,
    },
});
//# sourceMappingURL=prisma.config.js.map